path: modules/

modules:
  - name: core
    exposes:
      - mod.ts
    dependsOn:
      - util

  - name: util
    exposes:
      - mod.ts

  - name: persistence/core
    exposes:
      - mod.ts
    dependsOn:
      - core

  - name: persistence/postgres
    exposes:
      - mod.ts
    dependsOn:
      - persistence/core
