path: modules/

modules:
  - name: lib/json-equal
    exposes:
      - mod.ts

  - name: core
    exposes:
      - mod.ts
    dependsOn:
      - util
      - lib/json-equal

  - name: util
    exposes:
      - mod.ts

  - name: persistence/fs
    exposes:
      - mod.ts
    dependsOn:
      - core
